module scanner {
module generated {

const string WAFER_HEIGHTMAP_TOPIC = "WaferHeightMap";
const long MAX_MEASUREMENT_STEPS = 10000; // Maximum number of measurements for one wafer

struct Position
{
	double xPos;
	double yPos;
};

struct Measurement
{
	Position xyPosition;
	double zPos;
};

typedef sequence<Measurement,MAX_MEASUREMENT_STEPS> measurementsType;
@topic 
struct WaferHeightMap
{
	// ID of the heightmap whose measurements is being updated
	@key string heightMapID;  
	string waferID;  
	measurementsType measurements;
};

}; // generated
}; // scanner
